// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCF0thjKdj7DCZxXXpF4oGIsulxPqX8bA',
    appId: '1:16677004634:web:b9e8f65343a573bc533f63',
    messagingSenderId: '16677004634',
    projectId: 'loginapp-dce45',
    authDomain: 'loginapp-dce45.firebaseapp.com',
    storageBucket: 'loginapp-dce45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrGz7MJWkWm9LseZGqlvLoccNptZcCPJY',
    appId: '1:16677004634:android:cb75d062035013d5533f63',
    messagingSenderId: '16677004634',
    projectId: 'loginapp-dce45',
    storageBucket: 'loginapp-dce45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT9A1iqn3i6eLx6ATkczhfHJ_uTxZepgc',
    appId: '1:16677004634:ios:4c23742447093e1e533f63',
    messagingSenderId: '16677004634',
    projectId: 'loginapp-dce45',
    storageBucket: 'loginapp-dce45.appspot.com',
    iosClientId: '16677004634-vd7edr72kda86m8sdhum407lvem3uvdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT9A1iqn3i6eLx6ATkczhfHJ_uTxZepgc',
    appId: '1:16677004634:ios:5c354971741ab7a4533f63',
    messagingSenderId: '16677004634',
    projectId: 'loginapp-dce45',
    storageBucket: 'loginapp-dce45.appspot.com',
    iosClientId: '16677004634-mr5d1qqb3t2b4rlb4mfbv2mrpmgv4svd.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp.RunnerTests',
  );
}
